# Generated by Django 5.2.6 on 2025-12-27 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vouchers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serial_number", models.CharField(max_length=256)),
                ("pin", models.CharField(max_length=8)),
                ("valid_status", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Applicant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("undergraduate", "Undergraduate"),
                            ("postgraduate", "Postgraduate"),
                            ("sandwich", "Sandwich"),
                        ],
                        max_length=20,
                    ),
                ),
                ("personal_detail_completed", models.BooleanField(default=False)),
                ("history_completed", models.BooleanField(default=False)),
                ("choices_completed", models.BooleanField(default=False)),
                ("summary_completed", models.BooleanField(default=False)),
                ("emergency_contact_completed", models.BooleanField(default=False)),
                ("application_status", models.BooleanField(default=False)),
                (
                    "admission_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("rejected", "Rejected"),
                            ("admitted", "Admitted"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ApplicationUploads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("certificates", models.JSONField()),
                ("id_card", models.JSONField()),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_upload",
                        to="admissions.applicant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choices",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_choice", models.CharField()),
                ("second_choice", models.CharField()),
                ("third_choice", models.CharField()),
                ("remarks", models.TextField()),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_choices",
                        to="admissions.applicant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_history", models.JSONField()),
                ("work_experience", models.JSONField()),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_records",
                        to="admissions.applicant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PersonalDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gender", models.CharField()),
                ("marital_status", models.CharField()),
                ("date_of_birth", models.DateField()),
                ("nationality", models.CharField()),
                ("secondary_email", models.EmailField(max_length=254)),
                ("religion", models.CharField()),
                ("postal_address", models.CharField()),
                ("postal_country", models.CharField()),
                ("postal_region", models.CharField()),
                ("postal_town", models.CharField()),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applicant_details",
                        to="admissions.applicant",
                    ),
                ),
            ],
        ),
    ]
